# Generated by Django 5.2.14 on 2026-05-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouseitem",
            name="supplier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
