version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=dental_db
      - POSTGRES_USER=dental_user
      - POSTGRES_PASSWORD=dental_pass

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-mngdb#xhl3$zus7(355+5d-3a-lcoh978@adcq$(n%2kw6c)vv
      - DATABASE_URL=postgres://dental_user:dental_pass@db:5432/dental_db
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  postgres_data:
