# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="invoice_prefix",
            field=models.CharField(default="INV", max_length=20),
        ),
        migrations.AddField(
            model_name="lab",
            name="invoice_due_days",
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name="lab",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="lab",
            name="payment_method",
            field=models.CharField(default="bank_transfer", max_length=50),
        ),
        migrations.AddField(
            model_name="lab",
            name="invoice_default_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
