# Generated by Django 5.2.15 on 2026-06-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notification_filter_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadministrátor'), ('admin', 'Administrátor laboratória'), ('user', 'Používateľ'), ('technician', 'Technik')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Čaká'), ('accepted', 'Prijatá'), ('cancelled', 'Zrušená'), ('expired', 'Expirovaná')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadministrátor'), ('admin', 'Administrátor laboratória'), ('user', 'Používateľ'), ('technician', 'Technik')], default='user', max_length=20),
        ),
    ]
