# Generated by Django 5.2.15 on 2026-06-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_teaminvitation_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrolepermission',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrátor'), ('user', 'Používateľ'), ('technician', 'Technik')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('job', 'Práca'), ('invoice', 'Faktúra'), ('deadline', 'Termín'), ('stock', 'Sklad'), ('team', 'Tím'), ('system', 'Systém')], default='system', max_length=30),
        ),
    ]
