# Generated by Django 5.2.16 on 2026-08-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_lab_is_vat_payer"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="garant_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="lab",
            name="garant_registration_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
