# Generated by Django 5.2.16 on 2026-08-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_lab_garant_name_lab_garant_registration_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="label_prefix",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="lab",
            name="label_start_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
