# Generated by Django 5.2.17 on 2026-08-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_lab_label_prefix_lab_label_start_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="authorized_representative",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="lab",
            name="label_patient_identifier_mode",
            field=models.CharField(
                choices=[("name", "Meno pacienta"), ("code", "Kód pacienta")],
                default="name",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lab",
            name="mdr_declaration_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="lab",
            name="production_sites",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="lab",
            name="require_material_usage",
            field=models.BooleanField(default=False),
        ),
    ]
