# Generated by Django 5.2.17 on 2026-09-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_lab_authorized_representative_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
