# Generated by Django 5.2.17 on 2026-09-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_lab_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="skonto_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lab",
            name="skonto_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lab",
            name="skonto_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
