"""add_company_model

Revision ID: 7317c6e30b91
Revises: cdfe00462471
Create Date: 2025-10-19 17:35:42.670563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7317c6e30b91'
down_revision: Union[str, Sequence[str], None] = 'cdfe00462471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technicians', 'company_name')
    op.drop_column('technicians', 'bank_bic')
    op.drop_column('technicians', 'bank_account')
    op.drop_column('technicians', 'company_country')
    op.drop_column('technicians', 'company_address')
    op.drop_column('technicians', 'vat_id')
    op.drop_column('technicians', 'tax_id')
    op.drop_column('technicians', 'company_postal_code')
    op.drop_column('technicians', 'company_city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technicians', sa.Column('company_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('technicians', sa.Column('company_postal_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('technicians', sa.Column('tax_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('technicians', sa.Column('vat_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('technicians', sa.Column('company_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('technicians', sa.Column('company_country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('technicians', sa.Column('bank_account', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('technicians', sa.Column('bank_bic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('technicians', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
