"""add_email_to_users

Revision ID: 80b2322ebf26
Revises: 7d88cb559f4c
Create Date: 2025-10-21 10:53:49.568666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80b2322ebf26'
down_revision: Union[str, Sequence[str], None] = '7d88cb559f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    op.alter_column('clinics', 'lab_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('doctors', 'lab_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'lab_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('patients', 'lab_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.alter_column('patients', 'lab_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobs', 'lab_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('doctors', 'lab_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clinics', 'lab_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vat_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bank_account', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bank_bic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('companies_pkey'))
    )
    # ### end Alembic commands ###
