"""add_billing_info_to_technicians

Revision ID: cdfe00462471
Revises: 9e5f6c11e819
Create Date: 2025-10-19 17:31:19.289145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdfe00462471'
down_revision: Union[str, Sequence[str], None] = '9e5f6c11e819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technicians', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('technicians', sa.Column('company_address', sa.String(), nullable=True))
    op.add_column('technicians', sa.Column('company_city', sa.String(), nullable=True))
    op.add_column('technicians', sa.Column('company_postal_code', sa.String(), nullable=True))
    op.add_column('technicians', sa.Column('company_country', sa.String(), nullable=True))
    op.add_column('technicians', sa.Column('tax_id', sa.String(), nullable=True))
    op.add_column('technicians', sa.Column('vat_id', sa.String(), nullable=True))
    op.add_column('technicians', sa.Column('bank_account', sa.String(), nullable=True))
    op.add_column('technicians', sa.Column('bank_bic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technicians', 'bank_bic')
    op.drop_column('technicians', 'bank_account')
    op.drop_column('technicians', 'vat_id')
    op.drop_column('technicians', 'tax_id')
    op.drop_column('technicians', 'company_country')
    op.drop_column('technicians', 'company_postal_code')
    op.drop_column('technicians', 'company_city')
    op.drop_column('technicians', 'company_address')
    op.drop_column('technicians', 'company_name')
    # ### end Alembic commands ###
