# Generated by Django 5.2.14 on 2026-05-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_pricelist_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="document_type",
            field=models.CharField(
                choices=[("invoice", "Invoice"), ("proforma", "Proforma")],
                default="invoice",
                max_length=20,
            ),
        ),
    ]
