# Generated by Django 5.2.14 on 2026-05-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_add_invoice_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
