# Generated by Django 5.2.14 on 2026-05-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_add_invoice_vat_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="discount_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
