# Generated by Django 5.2.15 on 2026-06-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_invoice_filter_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Faktúra'), ('proforma', 'Proforma faktúra')], default='invoice', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Koncept'), ('issued', 'Vystavená'), ('paid', 'Zaplatená'), ('cancelled', 'Zrušená')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='category',
            field=models.CharField(blank=True, choices=[('crown', 'Korunka'), ('bridge', 'Mostík'), ('denture', 'Protéza'), ('implant', 'Implantát'), ('orthodontic', 'Ortodoncia'), ('repair', 'Oprava'), ('other', 'Iné')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Bezplatný'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Aktívne'), ('past_due', 'Po splatnosti'), ('cancelled', 'Zrušené'), ('inactive', 'Neaktívne')], default='inactive', max_length=20),
        ),
    ]
