# Generated by Django 5.2.16 on 2026-08-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_invoice_breakdown_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelist",
            name="default_insurance_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="default_patient_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="ipzp_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
