# Generated by Django 5.2.17 on 2026-08-22 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_lab_label_prefix_lab_label_start_number"),
        ("finance", "0013_pricelist_default_insurance_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="past_due_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_state_updated_at",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Aktívne"),
                    ("trialing", "Skúšobná doba"),
                    ("past_due", "Po splatnosti"),
                    ("cancelled", "Zrušené"),
                    ("inactive", "Neaktívne"),
                    ("read_only", "Iba na čítanie"),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("created", models.BigIntegerField(default=0)),
                ("handled", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, default="")),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stripe_events",
                        to="core.lab",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at", "-id"],
            },
        ),
    ]
