# Generated by Django 5.2.17 on 2026-09-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_subscription_past_due_since_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="paid_with_skonto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="skonto_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="skonto_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="skonto_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
