# Generated by Django 5.2.16 on 2026-07-17 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0015_lab_is_vat_payer"),
        ("inventory", "0003_warehouseitem_filter_index"),
        ("jobs", "0013_alter_calendarevent_event_type_alter_job_priority_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("prefix", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_manufacturers",
                        to="core.lab",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("unit", models.CharField(default="pcs", max_length=20)),
                (
                    "mdr_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Trieda I"),
                            ("IIa", "Trieda IIa"),
                            ("IIb", "Trieda IIb"),
                            ("III", "Trieda III"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("repeat", "Opakované použitie"),
                            ("single", "Jednorazové použitie"),
                        ],
                        default="repeat",
                        max_length=10,
                    ),
                ),
                ("allow_in_job", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_catalog",
                        to="core.lab",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="materials.manufacturer",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_catalog_entries",
                        to="inventory.warehouseitem",
                    ),
                ),
            ],
            options={
                "ordering": ["code", "id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_code", models.CharField(max_length=50)),
                ("lot", models.CharField(max_length=100)),
                ("received", models.DateField(default=django.utils.timezone.localdate)),
                ("expiry", models.DateField(blank=True, null=True)),
                ("opened", models.DateField(blank=True, null=True)),
                ("qty_received", models.DecimalField(decimal_places=3, max_digits=12)),
                ("qty_remaining", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktívna"),
                            ("open", "Otvorená"),
                            ("depleted", "Spotrebovaná"),
                            ("discarded", "Vyradená"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("location", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="materials.materialcatalog",
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_lots",
                        to="core.lab",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.OrderBy(models.F("expiry"), nulls_last=True),
                    "received",
                    "id",
                ],
            },
        ),
        migrations.CreateModel(
            name="MaterialRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("single", "Samostatná práca"),
                            ("bridge", "Mostík"),
                            ("arch", "Oblúk"),
                            ("other", "Iné"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("mdr", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_recipes",
                        to="core.lab",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_label", models.CharField(max_length=255)),
                (
                    "technician",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("recipe", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_usages",
                        to="jobs.job",
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_usages",
                        to="core.lab",
                    ),
                ),
                (
                    "recipe_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usages",
                        to="materials.materialrecipe",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialUsageLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_catalog_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "source_lot_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50)),
                ("manufacturer", models.CharField(max_length=255)),
                ("mdr_class", models.CharField(blank=True, max_length=10, null=True)),
                ("lot", models.CharField(max_length=100)),
                ("expiry", models.DateField(blank=True, null=True)),
                ("qty", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(max_length=20)),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="materials.materialusage",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RecipeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.DecimalField(decimal_places=3, max_digits=12)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_lines",
                        to="materials.materialcatalog",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="materials.materialrecipe",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="manufacturer",
            constraint=models.UniqueConstraint(
                fields=("lab", "prefix"), name="materials_unique_manufacturer_prefix"
            ),
        ),
        migrations.AddConstraint(
            model_name="materialcatalog",
            constraint=models.UniqueConstraint(
                fields=("lab", "code"), name="materials_unique_catalog_code"
            ),
        ),
        migrations.AddIndex(
            model_name="materiallot",
            index=models.Index(
                fields=["lab", "status", "expiry"], name="materials_lot_fefo_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="materiallot",
            constraint=models.UniqueConstraint(
                fields=("lab", "short_code"), name="materials_unique_lot_short_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="materiallot",
            constraint=models.UniqueConstraint(
                fields=("catalog", "lot"), name="materials_unique_catalog_lot"
            ),
        ),
        migrations.AddConstraint(
            model_name="materiallot",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_received__gt", 0)),
                name="materials_lot_received_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="materiallot",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_remaining__gte", 0)),
                name="materials_lot_remaining_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="materiallot",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_remaining__lte", models.F("qty_received"))),
                name="materials_lot_remaining_lte_received",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialrecipe",
            constraint=models.UniqueConstraint(
                fields=("lab", "name"), name="materials_unique_recipe_name"
            ),
        ),
        migrations.AddIndex(
            model_name="materialusage",
            index=models.Index(fields=["lab", "job"], name="materials_usage_job_idx"),
        ),
        migrations.AddConstraint(
            model_name="materialusageline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty__gt", 0)), name="materials_usage_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeline",
            constraint=models.UniqueConstraint(
                fields=("recipe", "catalog"), name="materials_unique_recipe_catalog"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty__gt", 0)), name="materials_recipe_qty_positive"
            ),
        ),
    ]
