"""add nickname to users and lab_id to vacations

Revision ID: 5df8f0906be3
Revises: 80b2322ebf26
Create Date: 2025-10-21 12:13:08.361002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df8f0906be3'
down_revision: Union[str, Sequence[str], None] = '80b2322ebf26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['nickname'])
    op.drop_column('users', 'username')
    op.add_column('vacations', sa.Column('lab_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacations', 'labs', ['lab_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacations', type_='foreignkey')
    op.drop_column('vacations', 'lab_id')
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'])
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
