# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_jobitem_procedure_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobitem",
            name="bridge_span",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="jobitem",
            name="color",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="jobitem",
            name="material",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="jobitem",
            name="tooth_state",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("missing", "Missing"),
                    ("implant", "Implant"),
                    ("temporary", "Temporary"),
                ],
                default="planned",
                max_length=30,
            ),
        ),
    ]
