# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_jobitem_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobitem",
            name="tooth_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "All teeth"),
                    ("U", "Upper jaw"),
                    ("L", "Lower jaw"),
                    ("Q1", "Quadrant 1"),
                    ("Q2", "Quadrant 2"),
                    ("Q3", "Quadrant 3"),
                    ("Q4", "Quadrant 4"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
