# Generated by Django 5.2.14 on 2026-05-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_jobitem_tooth_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtimelineevent",
            name="changed_fields",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
