# Generated by Django 5.2.15 on 2026-06-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_filter_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('meeting', 'Stretnutie'), ('pickup', 'Vyzdvihnutie'), ('delivery', 'Doručenie'), ('deadline', 'Termín'), ('other', 'Iné')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('low', 'Nízka'), ('normal', 'Bežná'), ('high', 'Vysoká'), ('urgent', 'Urgentná')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'Nová'), ('in_progress', 'V riešení'), ('completed', 'Dokončená'), ('cancelled', 'Zrušená'), ('finished_factured', 'Dokončená/fakturovaná'), ('finished_unfactured', 'Dokončená/nevyfakturovaná'), ('closed', 'Uzavretá')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobitem',
            name='procedure_category',
            field=models.CharField(blank=True, choices=[('crown', 'Korunka'), ('bridge', 'Mostík'), ('denture', 'Protéza'), ('implant', 'Implantát'), ('orthodontic', 'Ortodoncia'), ('repair', 'Oprava'), ('other', 'Iné')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobitem',
            name='tooth_scope',
            field=models.CharField(blank=True, choices=[('A', 'Všetky zuby'), ('U', 'Horná čeľusť'), ('L', 'Dolná čeľusť'), ('Q1', 'Kvadrant 1'), ('Q2', 'Kvadrant 2'), ('Q3', 'Kvadrant 3'), ('Q4', 'Kvadrant 4')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='jobitem',
            name='tooth_state',
            field=models.CharField(choices=[('planned', 'Plánované'), ('missing', 'Chýba'), ('implant', 'Implantát'), ('temporary', 'Dočasné')], default='planned', max_length=30),
        ),
    ]
