# Generated by Django 5.2.16 on 2026-08-21 23:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_lab_label_prefix_lab_label_start_number"),
        ("jobs", "0013_alter_calendarevent_event_type_alter_job_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="assigned_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="completed_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="diagnosis_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="job",
            name="handover_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="health_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="job",
            name="label_issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="label_number",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="received_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="seated_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobitem",
            name="insurance_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="jobitem",
            name="ipzp_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="jobitem",
            name="patient_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.CreateModel(
            name="ProstheticLabelSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
                (
                    "lab",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_sequence",
                        to="core.lab",
                    ),
                ),
            ],
        ),
    ]
