# Generated by Django 5.2.17 on 2026-08-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0015_backfill_job_lifecycle_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="contains_medicinal_substance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="medicinal_substance_note",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="safety_performance_deviations",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="jobtimelineevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("status_changed", "Status changed"),
                    ("assigned", "Assigned"),
                    ("deleted", "Deleted"),
                    ("label_issued", "Prosthetic label issued"),
                ],
                max_length=40,
            ),
        ),
    ]
